### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by omerlh** [Tarsnap/spiped#101]
Hey
Is there official support for windows? Or, as an alternaitve, C# client? I think I will be able to write something, but I would like some help to test it.

Thnaks 
Omer

**Comment by gperciva** [comment]
As stated in https://github.com/Tarsnap/spiped/blob/master/BUILDING, spiped is officially supported on:
```
any IEEE Std 1003.1 (POSIX) compliant system which
  1. Includes the Software Development Utilities option,
  2. Has OpenSSL available via -lcrypto and #include <openssl/foo>, and
  3. Provides /dev/urandom.
```

Cygwin can provide this.  I've heard vague talk of a "POSIX layer" in some versions of Windows, but I'm not familiar with them so I don't know whether they are actually valid POSIX or not.

**Comment by omerlh** [comment]
Ok thanks, I will try that.
On 4 Dec 2016, at 20:14, Graham Percival <notifications@github.com<mailto:notifications@github.com>> wrote:


As stated in https://github.com/Tarsnap/spiped/blob/master/BUILDING, spiped is officially supported on:

any IEEE Std 1003.1 (POSIX) compliant system which
  1. Includes the Software Development Utilities option,
  2. Has OpenSSL available via -lcrypto and #include <openssl/foo>, and
  3. Provides /dev/urandom.


Cygwin can provide this. I've heard vague talk of a "POSIX layer" in some versions of Windows, but I'm not familiar with them so I don't know whether they are actually valid POSIX or not.

**Comment by cperciva** [comment]
I think most of what spiped needs in the way of POSIX compatibility which is lacking in Windows is available via reasonably straightforward public domain shims.  You would need to write a `lib/util/entropy_windows.c` which makes the appropriate Windows API call for getting random numbers (CryptGenRandom, I think?) but if you're familiar with Windows development it shouldn't be too hard to get this working.

If you do get it working I'd definitely like to know -- I don't want to clog up the spiped source code, but if the changes needed are minimal enough (ideally, "add these files to the tree and a few lines of build instructions") then I'd definitely consider merging them, just like I include other workarounds for not-quite-POSIX systems.

**Comment by omerlh** [comment]
Ok, I will consider that.
On 5 Dec 2016, at 2:35, Colin Percival <notifications@github.com<mailto:notifications@github.com>> wrote:


I think most of what spiped needs in the way of POSIX compatibility which is lacking in Windows is available via reasonably straightforward public domain shims. You would need to write a lib/util/entropy_windows.c which makes the appropriate Windows API call for getting random numbers (CryptGenRandom, I think?) but if you're familiar with Windows development it shouldn't be too hard to get this working.

If you do get it working I'd definitely like to know -- I don't want to clog up the spiped source code, but if the changes needed are minimal enough (ideally, "add these files to the tree and a few lines of build instructions") then I'd definitely consider merging them, just like I include other workarounds for not-quite-POSIX systems.

**Comment by testcaoy7** [comment]
Cygwin works fine. I compiled spiped using babun.
