### ISSUE TITLE
Run screen command upon interactive login

### ISSUE THREAD

**Issue by 2devnull** [Tarsnap/spiped#156]
Similar to 'ssh -t' I guess, without messing with .zshrc and .bashrc remote files, how can I start a screen session (or reconnect to existing one) upon login?

Thank you.

**Comment by gperciva** [comment]
Sorry, I'm not certain if you asked this question in the right place.  How does `screen` relate to `spiped`?

**Comment by 2devnull** [comment]
ok, spipe/spiped give me the connection to the remote server. Once there, I would then link spiped to run a command (in this case Screen or Tmux) so if I get disconnected, I can get back to my session with its context intact. 

Partially related, but this [article] (https://mcneill.io/autossh/)tries to summarize some options for this using some other tools. Since I use spipe/spiped already to connect to my remotes hosts, I was wondering how I can run commands on the remote server automatically.

**Comment by gperciva** [comment]
`spiped` gives you a pipe to a socket (generally one on a remote machine).  It's not a shell connection, so `spiped` cannot "run a command" by itself.

What you could do is to use `spiped` to protect an SSH connection, as mentioned in the README.md or a number of blog posts found from a quick google search:
http://www.daemonology.net/blog/2012-08-30-protecting-sshd-using-spiped.html
https://www.vultr.com/docs/protect-ssh-access-using-spiped-on-openbsd
https://github.com/morgante/spiped-docker/blob/master/readme.md
Then you could use `ssh` to run whatever command(s) you want.

**Comment by cperciva** [comment]
Or possibly use something like `inetd` or `tcpserver` to launch screen/tmux.

**Comment by 2devnull** [comment]
@gperciva  - Yes, I am already protecting ssh with spiped using ProxyCommand. I didn't see a way how to run a command, e.g.:

```
Host myhost
	User myuser
	ProxyCommand spipe -t %h:28748 -k /home/spiped/mykey.key
```

**Comment by 2devnull** [comment]
@cperciva - I'll look into this, however do you have a reference, on top of my head, not sure how those would do this. Thanks.

**Comment by cperciva** [comment]
Sounds like you just want to run `ssh myhost screen` then?

On 01/05/18 13:53, 2devnull wrote:
> @gperciva <https://github.com/gperciva> - Yes, I am already protecting ssh
> with spiped using ProxyCommand. I didn't see a way how to run a command, e.g.:
> 
> |Host myhost User myuser ProxyCommand spipe -t %h:28748 -k /home/spiped/mykey.key |

-- 
Colin Percival
Security Officer Emeritus, FreeBSD | The power to serve
Founder, Tarsnap | www.tarsnap.com | Online backups for the truly paranoid

**Comment by 2devnull** [comment]
@cperciva - yes!

**Comment by 2devnull** [comment]
ok, I believe you have put me on the correct path and now doing this I can connect.

`ssh -t myhost screen -R -d`
