### ISSUE TITLE
"Address must contain port number" in cygwin environment

### ISSUE THREAD

**Issue by ivan** [Tarsnap/spiped#16]
Not sure what's going on here.

```
# spiped -d -s '[0.0.0.0]:8025' -t '[127.0.0.1]:25' -k keyfile
: Address must contain port number:
zsh: abort (core dumped)  spiped -d -s '[0.0.0.0]:8025' -t '[127.0.0.1]:25' -k keyfile
```

**Comment by ivan** [comment]
Some print debugging reveals that `strdup` on https://github.com/Tarsnap/spiped/blob/5ed45470feda5063e33da48f0088e99fb666b82b/libcperciva/util/sock.c#L244 is setting `s` to a 0-length string

**Comment by ivan** [comment]
Pasting in and using a working `strdup` implementation fixes that particular problem and seems to be enough to get spiped running in cygwin.

**Comment by ivan** [comment]
Don't know why `strdup` is behaving incorrectly in sock.c; it seems to work in a small demo program compiled under gcc in cygwin.

**Comment by ivan** [comment]
Oh, duh, I really should have read the warnings in the compile output indicating that `strdup` was being implicitly defined.

Anyway, the `-D_POSIX_C_SOURCE=200809L` in your Makefiles is what's stopping cygwin from referencing its `strdup` implementation.

**Comment by cperciva** [comment]
Correct me if I'm wrong, but doesn't POSIX require that strdup exists and is declared by <string.h> ?

**Comment by ivan** [comment]
Yeah, this is probably a cygwin `newlib/libc/include/string.h` issue.  They're defining `strdup` only on

```
#if __XSI_VISIBLE >= 500
char    *_EXFUN(strdup,(const char *));
#endif
```

where `__XSI_VISIBLE >= 500` when

```
#elif _XOPEN_SOURCE - 0 >= 500
#define __XSI_VISIBLE       500
```
(newlib/libc/include/sys/cdefs.h)

It's possible that autoconf configures are setting `_XOPEN_SOURCE`, so not many run into this.

**Comment by cperciva** [comment]
I've just been digging through their source tree -- yes, definitely a cygwin bug.  They need to expose strdup (and several other functions) for

#if __POSIX_VISIBLE >= 200112 || __XSI_VISIBLE >= 500

Do you want to file a bug with cygwin, or shall I?

**Comment by ivan** [comment]
Please go ahead and tell newlib@sourceware.org, it sounds like you know more than I do about which additional functions should be exposed and to which POSIX versions :-)

**Comment by cperciva** [comment]
Will do.  Thanks for your help!

**Comment by cperciva** [comment]
Is there anything which could be added to BUILDING to help cygwin users here?  I don't know if

# sed -i .orig s/-D_POSIX_C_SOURCE=200809L// */Makefile

would fix the problem?

**Comment by ivan** [comment]
Yeah, that fixes the problem for cygwin users.  Note that you need

```
sed -i.orig s/-D_POSIX_C_SOURCE=200809L// */Makefile
```

no space before the `.orig`

**Comment by cperciva** [comment]
Thanks, I've added that documentation to BUILDING.  Hopefully Cygwin users will read that far...
