### ISSUE TITLE
build failure on arm32v6?

### ISSUE THREAD

**Issue by TimWolla** [Tarsnap/spiped#166]
I recently updated the README of the spiped Dockerfile repository to match the ones of other official images: https://github.com/TimWolla/docker-spiped

The new README shows the build status of the image on various architectures, among them arm32v6 which is the only architecture that fails to build the spiped Docker image.

An example output can be found here: https://doi-janky.infosiftr.net/job/multiarch/job/arm32v6/job/spiped/34/console

The relevant excerpt is as follows:

```
+ CC=gcc make -C /usr/local/src/spiped
make: Entering directory '/usr/local/src/spiped'
( export CC="gcc"; command -p sh libcperciva/cpusupport/Build/cpusupport.sh "$PATH" ) > cpusupport-config.h
Checking if compiler supports X86 CPUID feature... no
Checking if compiler supports X86 AESNI feature... no
export CFLAGS="${CFLAGS:--O2}";	\
export LDADD_POSIX=`export CC="gcc"; cd libcperciva/POSIX && command -p sh posix-l.sh "$PATH"`;	\
export CFLAGS_POSIX=`export CC="gcc"; cd libcperciva/POSIX && command -p sh posix-cflags.sh "$PATH"`;	\
. ./cpusupport-config.h;			\
for D in spiped spipe tests/nc-client tests/nc-server tests/valgrind; do			\
	( cd ${D} && make all ) || exit 2;	\
done
make[1]: Entering directory '/usr/local/src/spiped/spiped'
gcc -O2  -D_POSIX_C_SOURCE=200809L -DCPUSUPPORT_CONFIG_FILE=\"cpusupport-config.h\"  -I.. -I../proto -I../libcperciva/alg -I../libcperciva/datastruct -I../lib/dnsthread -I../lib/util -I../libcperciva/util -I../libcperciva/cpusupport -I../libcperciva/events -I../libcperciva/network -I../libcperciva/crypto -c main.c -o main.o
main.c: In function 'parsenum_float':
main.c:368:1: internal compiler error: Illegal instruction
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[1]: *** [Makefile:33: main.o] Error 1
make[1]: Leaving directory '/usr/local/src/spiped/spiped'
make: Leaving directory '/usr/local/src/spiped'
make: *** [Makefile:9: all] Error 2
```

The corresponding line in the Dockerfile is this: https://github.com/TimWolla/docker-spiped/blob/4c5ed8edd93bab152cd34cc1bf837bab8b8fa882/1.6/alpine/Dockerfile#L25

I have no idea whether this issue is with spiped, gcc or somewhere else. I don't have an arm32v6 machine handy to compile it outside of Docker myself, either.

Thus I'm just reporting it here to make you aware of it.

**Comment by gperciva** [comment]
In case anybody stumbles across this issue, here's the relevant function from spiped:

```
/* Functions for performing the parsing and parameter checking. */
static inline double
parsenum_float(const char * s, double min, double max)
{
        char * eptr;
        double val;

        val = strtod(s, &eptr);
        if ((eptr == s) || (*eptr != '\0'))
                errno = EINVAL;
        else if ((val < min) || (val > max))
                errno = ERANGE;
        return (val);
}
```

As the log-file suggests, I suspect an internal compiler error rather than a problem in the spiped source code.  Or possibly a problem in the implementation of `strtod()`?

**Comment by yosifkit** [comment]
Yeah, we've seem similar issues: https://github.com/docker-library/postgres/issues/420, https://github.com/docker-library/golang/issues/196, https://github.com/docker-library/memcached/issues/25, and https://github.com/docker-library/busybox/pull/41.  We use an arm64v8 server to build the arm32v6 images and in a few places it seems it is not 100% compatible with arm32v6 instructions.

@tianon, can we special case `spiped` to build elsewhere like `golang`, `postgres`, and `vault`?

**Comment by tianon** [comment]
Yeah, absolutely: https://github.com/docker-library/oi-janky-groovy/pull/4 :+1:

**Comment by cperciva** [comment]
Sounds like this issue can be closed, since it's not really an spiped issue and has been worked around anyway?

**Comment by tianon** [comment]
Yeah, that seems accurate 👍

**Comment by tianon** [comment]
See https://github.com/docker-library/oi-janky-groovy/commit/5141c15b1ba4ced1617a6150f625e46d573d62f9 :tada: :cake: :metal:
