### ISSUE TITLE
no version for windows ?

### ISSUE THREAD

**Issue by wjkhappy14** [Tarsnap/spiped#176]
How to run  it on Windows？

**Comment by gperciva** [comment]
As per the https://github.com/Tarsnap/spiped/blob/master/BUILDING file,

Spiped should build and run on any IEEE Std 1003.1 (POSIX) compliant
system which
  1. Includes the Software Development Utilities option,
  2. Has OpenSSL available via -lcrypto and #include <openssl/foo>, and
  3. Provides /dev/urandom.

If your version of Windows supplies that, please give more information about what compiler error you saw.

If the above doesn't make sense to you, I suspect that spiped is not the software that you're looking for.

**Comment by testcaoy7** [comment]
Can be compiled under Cygwin or you can use Linux subsystem on Windows 10.
