### ISSUE TITLE
OPT_EPARSE bug

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/spiped#178]
Looks like this wasn't adjusted when `ch` changed from being a character to a string?

https://github.com/Tarsnap/spiped/blob/5eab671e0edfcf206f20827cc2d4a3a64d552268/spiped/main.c#L60

**Comment by cperciva** [comment]
Same bug exists all over the place in kivaloo.

**Comment by gperciva** [comment]
Fixed in #179, and PR for kivaloo is https://github.com/Tarsnap/kivaloo/pull/47.
