### ISSUE TITLE
Unable to compile spiped on OpenSUSE 42.2

### ISSUE THREAD

**Issue by randyrue** [Tarsnap/spiped#181]
Hi There,

On a pretty stock install of OpenSUSE Leap 42.2 including gcc I'm unable to run make within the spiped directory after extracting the tarball.

Something appears to be passing invalid arguments to the "c99" command:
```
c99 -O2  -D_POSIX_C_SOURCE=200809L -DCPUSUPPORT_CONFIG_FILE=\"cpusupport-config.h\"  -I.. -I../proto -I../libcperciva/alg -I../libcperciva/datastruct -I../lib/dnsthread -I../lib/util -I../libcperciva/util -I../libcperciva/cpusupport -I../libcperciva/events -I../libcperciva/network -I../libcperciva/crypto -c main.c -o main.o
c99: invalid option -- '2'
usage: c99 [-c] [-D name[=value]] [...] [-E] [-g] [-I directory ...]
       [-L directory ...] [-o outfile] [-O] [-s] [-U name ...] operand ...

       where operand is one or more of file.c, file.o, file.a
       or -llibrary
```
from the man page for c99 I can't see any way that "-O2" could be a valid argument?

**Comment by cperciva** [comment]
Looks like a bug in OpenSUSE to me: POSIX says that c99 takes a `-O  optlevel` option: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/c99.html

**Comment by gperciva** [comment]
That's not how I read it.  I think it must support `0` and `1`.  If the system wants to support other digits, that's not a violation.  But I don't think that systems are required to support `5` or `3.141`.

```
-O  optlevel
Specify the level of code optimization. If the optlevel option-argument is the digit '0', all special code optimizations shall be disabled. If it is the digit '1', the nature of the optimization is unspecified. If the -O option is omitted, the nature of the system's default optimization is unspecified. It is unspecified whether code generated in the presence of the -O 0 option is the same as that generated when -O is omitted. Other optlevel values may be supported.
```

**Comment by randyrue** [comment]
with or without a space? The 6th line of the Makefile says "CFLAGS_DEFAULT=        -O2"
When I remove the 2 it compiles, also if I change it tp -O 2

**Comment by gperciva** [comment]
@randyrue: what happens if you make it `-O1` ?  I'm also curious about something like `c99 -omybin foo.c` -- does the compiler support any arg without a space?

**Comment by randyrue** [comment]
Looks like whatever implementation of c99 SUSE installs does include the -O argument but doesn't mention a following argument. Not my favorite distro but no other options in this case.

Thanks!

**Comment by gperciva** [comment]
Let's not close this yet -- I think that strictly speaking, we can't rely on `-O2` working, and we try to maintain strict POSIX compatibility.  Let's see if @cperciva reads the standard in a different way than I do.

**Comment by gperciva** [comment]
@randyrue BTW, you should be able to get your favourite compiler to work in C99 mode by adding `-std=c99` to the args.  For example,

```
CC="clang -std=c99" make
CC="gcc -std=c99" make
```

**Comment by cperciva** [comment]
My reading of POSIX is that `-O2` isn't guaranteed to work, but that `c99` should at least recognize it as an option.  The error message suggests that it isn't realizing that `-O` can have a parameter.

**Comment by gperciva** [comment]
Hmm, ok.
