### ISSUE TITLE
Unable to compile spiped on SLES11 SP3

### ISSUE THREAD

**Issue by randyrue** [Tarsnap/spiped#189]
Hi Again,

I suspect this is a variation on the compile errors with OpenSUSE I opened an issue for last November, and again related to quirks in the host OS, but would be grateful for any guidance.

I'm trying to compile spiped for a legacy SLES 11 SP3 host. The "posix_cc" package is installed along with gcc and it's list of partner packages.

If I cd into the extracted spiped tarball directory and just run 'make install' I get:
```
xapps-dev2root@xapps-dev2:~/spiped-1.6.0# make install
export CFLAGS="${CFLAGS:--O2}"; \
        export LDADD_POSIX=`export CC="cc"; cd libcperciva/POSIX && command -p sh posix-l.sh "$PATH"`;  \
        export CFLAGS_POSIX=`export CC="cc"; cd libcperciva/POSIX && command -p sh posix-cflags.sh "$PATH"`;    \
        . ./cpusupport-config.h;                        \
        for D in spiped spipe tests/nc-client tests/nc-server tests/valgrind; do                        \
                ( cd ${D} && make all ) || exit 2;      \
        done
WARNING: POSIX violation: /bin/bash's command -p resets $PATH
WARNING: POSIX violation: make's CC doesn't understand -lxnet
WARNING: POSIX violation: /bin/bash's command -p resets $PATH
WARNING: POSIX violation: cc does not accept 'restrict' keyword
/root/spiped-1.6.0/spiped
make[1]: Entering directory `/root/spiped-1.6.0/spiped'
cc -O2 /root/spiped-1.6.0/libcperciva/POSIX
/root/spiped-1.6.0/libcperciva/POSIX: file not recognized: Is a directory
collect2: ld returned 1 exit status
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/root/spiped-1.6.0/spiped'
make: *** [all] Error 2
xapps-dev2root@xapps-dev2:~/spiped-1.6.0#
```

This time the "cc -O2" doesn't seem to be the problem, as it was for OpenSUSE.
I've also tried 'CC="gcc -std=c99" make install' on a guess from your previous posts, and the process makes it considerably further before failing at the same "file not recognized" error.

Again, any guidance would be great...

Randy
Seattle

**Comment by gperciva** [comment]
Right.  The red flag is this line:

```
cc -O2 /root/spiped-1.6.0/libcperciva/POSIX
```

However, I'm puzzled as to how the makefile produces that line.

Could you please run:
```
echo $CC
echo $CFLAGS
echo $CFLAGS_POSIX
```

and let me know if you see anything?  I'm expecting those to produce blank output.

If you don't see anything suspicious in those lines, please try:

    make -n

and show me the first few lines to that (enough to include the two "compiling" lines).

**Comment by gperciva** [comment]
Another small possibility: we changed the way that the build system handles `libcperciva/POSIX` a few months ago in git.  It's unlikely, but if you have the git repository and the tarball in the same directory, I could imagine it getting very confused.

At the moment I'm assuming that you're dealing with the official spiped-1.6.0 tarball, but please let me know if you're looking at git master instead.

**Comment by randyrue** [comment]
Thanks for your quick reply, I've also been poking around in the makefiles trying to figure out where it's calling cc with that directory but I don't know much about it.

Those env variables are indeed all empty.

I did have the tarball file in the same directory as the extracted directory but not a pulled github directory. I've removed the tgz file to be sure but get the same error on 'make install.'

'make -n' returns:
```
xapps-dev2root@xapps-dev2:~/spiped-1.6.0# make -n
( export CC="cc"; command -p sh libcperciva/cpusupport/Build/cpusupport.sh "$PATH" ) > cpusupport-config.h
export CFLAGS="${CFLAGS:--O2}"; \
        export LDADD_POSIX=`export CC="cc"; cd libcperciva/POSIX && command -p sh posix-l.sh "$PATH"`;  \
        export CFLAGS_POSIX=`export CC="cc"; cd libcperciva/POSIX && command -p sh posix-cflags.sh "$PATH"`;    \
        . ./cpusupport-config.h;                        \
        for D in spiped spipe tests/nc-client tests/nc-server tests/valgrind; do                        \
                ( cd ${D} && make all ) || exit 2;      \
        done
WARNING: POSIX violation: /bin/bash's command -p resets $PATH
WARNING: POSIX violation: make's CC doesn't understand -lxnet
WARNING: POSIX violation: /bin/bash's command -p resets $PATH
WARNING: POSIX violation: cc does not accept 'restrict' keyword
/bin/sh: line 3: ./cpusupport-config.h: No such file or directory
make: *** [all] Error 1
xapps-dev2root@xapps-dev2:~/spiped-1.6.0#
```

**Comment by gperciva** [comment]
Thanks!  For my sanity, please rename that directory to be `spiped` instead of `spiped-1.6.0`.  :)
We changed a few things in the build system after 1.6.0, so that will keep my attention on the git repository instead of the system we had in 1.6.0.

To eliminate one problem, let's try this:
```
make clean
make posix-flags.sh
make cpusupport-config.h
```

Based on the first set of logs, that should complete with no problem.  Then please send me the result of:

```
more posix-flags.sh
```

**Comment by randyrue** [comment]
I've removed and re-extracted the spiped directory, renamed it to 'spiped' and cd'd into it:
```
xapps-dev2root@xapps-dev2:~/spiped# pwd
/root/spiped
xapps-dev2root@xapps-dev2:~/spiped# make posix-flags.sh
make: *** No rule to make target `posix-flags.sh'.  Stop.
xapps-dev2root@xapps-dev2:~/spiped# make cpusupport-config.h
( export CC="cc"; command -p sh libcperciva/cpusupport/Build/cpusupport.sh "$PATH" ) > cpusupport-config.h
WARNING: POSIX violation: /bin/bash's command -p resets $PATH
Checking if compiler supports X86 CPUID feature... yes
Checking if compiler supports X86 AESNI feature... yes, via -maes
xapps-dev2root@xapps-dev2:~/spiped# make posix-cflags.sh
make: *** No rule to make target `posix-cflags.sh'.  Stop.
xapps-dev2root@xapps-dev2:~/spiped# make posix-flags.h
make: *** No rule to make target `posix-flags.h'.  Stop.
xapps-dev2root@xapps-dev2:~/spiped# make posix-cflags.h
make: *** No rule to make target `posix-cflags.h'.  Stop.
xapps-dev2root@xapps-dev2:~/spiped#
```

I'm not seeing any references in the Makefile to posix-flags.sh but do see some for posix-cflags.sh so I tried some variations on that with no luck...

**Comment by randyrue** [comment]
FWIW, posix-cflags.sh already existed and looks like:
```
# Should be sourced by `command -p sh posix-cflags.sh "$PATH"` from within a Makefile
if ! [ ${PATH} = "$1" ]; then
        echo "WARNING: POSIX violation: $SHELL's command -p resets \$PATH" 1>&2
        PATH=$1
fi
FIRST=YES
if ! ${CC} -D_POSIX_C_SOURCE=200809L posix-msg_nosignal.c 2>/dev/null; then
        [ ${FIRST} = "NO" ] && printf " "; FIRST=NO
        printf %s "-DPOSIXFAIL_MSG_NOSIGNAL"
        echo "WARNING: POSIX violation: <sys/socket.h> not defining MSG_NOSIGNAL" 1>&2
fi
if ! ${CC} -D_POSIX_C_SOURCE=200809L posix-clock_realtime.c 2>/dev/null; then
        [ ${FIRST} = "NO" ] && printf " "; FIRST=NO
        printf %s "-DPOSIXFAIL_CLOCK_REALTIME"
        echo "WARNING: POSIX violation: <time.h> not defining CLOCK_REALTIME" 1>&2
fi
if ! ${CC} -D_POSIX_C_SOURCE=200809L posix-restrict.c 2>/dev/null; then
        echo "WARNING: POSIX violation: ${CC} does not accept 'restrict' keyword" 1>&2
        if ${CC} -D_POSIX_C_SOURCE=200809L -std=c99 posix-restrict.c 2>/dev/null; then
                [ ${FIRST} = "NO" ] && printf " "; FIRST=NO
                printf %s "-std=c99"
        fi
fi
rm -f a.out
```

**Comment by gperciva** [comment]
My apologies, I misread an earlier message.  You're working with the spiped-1.6.0 tarball, not git, so `posix-flags.sh` was a red herring.

I'm currently looking for an opensuse 11.1 release iso (since that seems to be the "base" of SLES 11) so that I can install and test it locally.

Another idea is to edit the top-level Makefile.  Instead of:

```
all: cpusupport-config.h
        export CFLAGS="$${CFLAGS:-${CFLAGS_DEFAULT}}";  \
        export LDADD_POSIX=`export CC="${CC}"; cd libcperciva/POSIX && command -p sh posix-l.sh "$$PATH"`;      \
        export CFLAGS_POSIX=`export CC="${CC}"; cd libcperciva/POSIX && command -p sh posix-cflags.sh "$$PATH"`;        \
        . ./cpusupport-config.h;                        \
        for D in ${PROGS} ${TESTS}; do                  \
                ( cd $${D} && ${MAKE} all ) || exit 2;  \
        done
```

please delete the last three lines and make it:
```
all: cpusupport-config.h
        export CFLAGS="$${CFLAGS:-${CFLAGS_DEFAULT}}";  \
        export LDADD_POSIX=`export CC="${CC}"; cd libcperciva/POSIX && command -p sh posix-l.sh "$$PATH"`;      \
        export CFLAGS_POSIX=`export CC="${CC}"; cd libcperciva/POSIX && command -p sh posix-cflags.sh "$$PATH"`;        \
        echo ${CFLAGS}; \
        echo ${CFLAGS_POSIX}; \
        echo ${LDADD_POSIX};
```

I'm wondering if those variables became corrupted somehow, because at the moment that's my best guess as to why the makefile is trying to compile a directory.

**Comment by gperciva** [comment]
Update: I've installed opensuse 11.1 and compiled spiped.  So no help there in tracking down the problem.

I think the next step is to examine the `CFLAGS` and `CFLAGS_POSIX` variables at the end of the "all" block in the Makefile, as I suggested above.

Another option would be to try using git master, which significantly changed the way we handle posix compatibility.

**Comment by randyrue** [comment]
I believe I've wasted your time. If I su to my (unprivileged) account on the same host and make/install to my own bin folder, it succeeds with no arguments. Gah.

This should be the last time I need to build your fine service on any old hosts. From now on it's just 'apt-get install spiped.'

**Comment by gperciva** [comment]
Ok, glad it worked out!  The log looks like it needs a "-std=c99" or "CC=c99" or something like that, but perhaps your user account has that configured automatically.

If nothing else, this confirms that the changes we made after 1.6.0 are useful -- they would make it easier to identify problems like this.
