### ISSUE TITLE
version

### ISSUE THREAD

**Issue by nerijus** [Tarsnap/spiped#200]
I compiled latest 1.6.0 release on CentOS 7, and running ./spipe -v shows:
```
spipe @VERSION@
```

**Comment by nerijus** [comment]
Ah, it's from github downloaded version. https://www.tarsnap.com/spiped/spiped-1.6.0.tgz shows correct version.

**Comment by gperciva** [comment]
Yes, the version string is added as part of the release process.

**Comment by Bacto** [comment]
It would be great to be able to pass the version on compilation time, with `make VERSION=x.y.z BINDIR=/path/to/target/directory install`
