### ISSUE TITLE
Support PREFIX, DESTDIR?

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/spiped#234]
It would be nice if we could support `PREFIX`, i.e.

```
make PREFIX=$HOME/.local/ install
```

It would be easy enough to automatically set `BINDIR=${PREFIX}/bin`.  However, `MAN1DIR` is a problem.  Many OSes expect that to be `${PREFIX}/share/man/man1`, but FreeBSD doens't have a `/usr/local/share/man`; instead, their `heir(7)` clearly documents that this should be `/usr/local/man` instead.

So it's probably best to keep `BINDIR` and `MAN1DIR` separate and let packages set them as appropriate.  (Also, that allows us to indicate whether to install man-pages in addition to the binary.)

On a similar note, may build systems support a `DESTDIR`, such as

```
BINDIR=${DESTDIR}${PREFIX}/bin
```

This is similiar to FreeBSD's "staging"[1][2].  But again, it's probably safest to leave that to packagers to play with.

[1] https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/porting-prefix.html
[2] https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/special.html#staging

[I opened this issue to keep track of any future developments or discussion about this; at the moment I don't think that we can make any changes cleanly.]

**Comment by cperciva** [comment]
I deliberately avoided this, due to the range of different paths which packaging systems want.  In the FreeBSD port I have
```
MAKE_ARGS+=     BINDIR=${STAGEDIR}${PREFIX}/bin
MAKE_ARGS+=     MAN1DIR=${STAGEDIR}${PREFIX}/man/man1
```
for example.

I think it would be better if Debian passed in the paths as make environment variables rather than patching things, but that's up to them...
