### ISSUE TITLE
Version 1.6.1 not released?

### ISSUE THREAD

**Issue by Bacto** [Tarsnap/spiped#238]
Hi,

First thank you for this really great project!

The version 1.6.1 is available in the changelog file (https://github.com/Tarsnap/spiped/blob/master/CHANGELOG) but it doesn't have been released (https://github.com/Tarsnap/spiped/releases).
Is it normal or is it an oversight?

Thanks,
Adrien

**Comment by gperciva** [comment]
Oops, my mistake.  That file should contain
```
spiped-1.6.1 (unreleased)
```

The release process will begin with a 1-week alpha testing period, announced on the `tarsnap-alphatest` and `spiped` mailing lists, and if that passes then we'll make the official release, update the website, announce it on those lists, etc.
http://www.tarsnap.com/lists.html

**Comment by Bacto** [comment]
Super serious way of testing/validating a new release, I like it!
Thank you @gperciva :)
