### ISSUE TITLE
Why This Instead of IPSec Tunnels 

### ISSUE THREAD

**Issue by Librechain** [Tarsnap/spiped#282]
Not trying to rip down your tool or say that it isn't necessary, it just seems that IPSec tunnels would be more suitable within the scheme that you're creating here with Tarsnap. https://github.com/Tarsnap/spiped

Specifically, I'm referring to LibreSwan or StrongSwan (either or) 

Forgive my ignorance if I'm wrong on this. And if I am, I would definitely love to be enlightened. Perhaps I'm not understanding correctly here.

**Comment by cperciva** [comment]
IPSec works at a completely different layer -- it relies on the kernel IP stack to encrypt and decrypt packets.  That's a far more heavyweight solution than spiped, which runs entirely in userland.  Also, spiped supports unix sockets.

**Comment by Librechain** [comment]
Ah, makes sense. Thank you for that explanation.
