### ISSUE TITLE
It does re-resolution, does it?

### ISSUE THREAD

**Issue by x-yuri** [Tarsnap/spiped#402]
From what I can see, it [does][a], but the docs is kind of [vague][b] about it.

[a]: https://github.com/Tarsnap/spiped/commit/2185e3b0cd4b313ab654793d111a3347082f987b
[b]: https://github.com/Tarsnap/spiped/blob/52e77d0340340b7b627c307c2121551da0f3f0c7/spiped/spiped.1#L68-L72

**Comment by cperciva** [comment]
The target address (where spiped connects to) will be re-resolved, but not the source address (where spiped listens for incoming connections).

**Comment by x-yuri** [comment]
Oh, my bad then. I guess I wasn't reading attentively.
