### ISSUE TITLE
Is it safe to use text encoded key?

### ISSUE THREAD

**Issue by ddribin** [Tarsnap/spiped#403]
This is more of question, but do you think it is safe to use a text (ASCII) encoded key? For example:

```
> dd if=/dev/urandom bs=32 count=1 of=sshd.key
1+0 records in
1+0 records out
32 bytes copied, 0.000310038 s, 103 kB/s
> xxd -ps -c32 sshd.key
69b65bf265b17cf9d297180464f67a80530a6c6f33bd7e8d97704fdfe99b2320
> base64 sshd.key
abZb8mWxfPnSlxgEZPZ6gFMKbG8zvX6Nl3BP3+mbIyA=
```

Is it safe to use the hex or Base64 encoded text *as* the key? In other words, replace the `sshd.key` contents with this text and use that as the key file passed to `spiped -k`, like such:

```
dd if=/dev/urandom bs=32 count=1 | xxd -ps -c32 > sshd.key
# Or:
dd if=/dev/urandom bs=32 count=1 | base64 > sshd.key
```

Will this somehow weaken the key or `spipe` communication, compared to a binary key? I am assuming it is just as secure, since it's still just random data and `spiped` will use all the bytes of the key file, but I wanted to get your opinion on this.

I ask because it is easier to store text in password/secret managers than binary blobs.

**Comment by cperciva** [comment]
Yes, that's just fine.  They key file could even be e.g. English text; you're safe as long as there's enough total entropy.

**Comment by ddribin** [comment]
Great, thank you!

Also wanted to say "thank you" for `spiped`. I've been using it since around 2018.

**Comment by ddribin** [comment]
I just wanted to add that that, if you do use a text encoded key, be careful to match trailing newlines on both the client and the server. If you're just copying the file, it's pretty straightforward. But if you store the text key in a password manager, be sure it adds a newline (or not), to match the server's key. Don't ask how I know this...
