### ISSUE TITLE
opt_n limit 500

### ISSUE THREAD

**Issue by carlhopf** [Tarsnap/spiped#82]
spiped won't allow values for -n over 500. is there any reason or history for that behaviour?

i believe it would be better if we could choose any number we deem suitable for our projects. this limit prevents me from deploying spiped across my infrastructure.

thanks

**Comment by cperciva** [comment]
See https://github.com/Tarsnap/spiped/issues/24 and https://github.com/Tarsnap/libcperciva/issues/6 .  Patches welcome.

**Comment by carlhopf** [comment]
thanks, i'll look into the existing thread and close this one.

**Comment by cperciva** [comment]
FWIW, patches in #112
